### PR TITLE
Improved ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
cf commit list

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
I can take care to do the migration to `code`

**Comment by geek** [comment]
looks good overall, looks like travis has issues with some of the dependencies though :/

**Comment by AdrieanKhisbe** [comment]
> npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package seneca@0.9.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer seneca-mem-store@0.4.0 wants seneca@*
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/senecajs/seneca-store-test/npm-debug.log
The command "eval npm install " failed. Retrying, 2 of 3.

mmmmmm....

**Comment by AdrieanKhisbe** [comment]
It's because of :

```json
  "peerDependencies": {
    "seneca": ">=0.8.0 <0.9.0"
  }
```

How should I kill this?

**Comment by geek** [comment]
We should make it `">=0.8.0 <=1.x.x"

**Comment by AdrieanKhisbe** [comment]
Okey dokey dokey!
incoming

**Comment by AdrieanKhisbe** [comment]
et voilà.

**Comment by AdrieanKhisbe** [comment]
damnit

**Comment by AdrieanKhisbe** [comment]
strange strange:
https://travis-ci.org/senecajs/seneca-store-test/jobs/101909234
@geek could you try to relaunch the build? :smil

**Comment by AdrieanKhisbe** [comment]
`Peer seneca-mem-store@0.4.0 wants seneca@*`

**Comment by AdrieanKhisbe** [comment]
Might be npm being a pain.

Shall I change this: https://github.com/senecajs/seneca-mem-store/blob/master/package.json#L40-L42?

**Comment by geek** [comment]
ya, mind testing locally with 0.10 and see what works

**Comment by AdrieanKhisbe** [comment]
Add some *Works on my machine*, then found a tweak!

**Pull request merged**
